### ISSUE TITLE
Dump and show offset of native class/struct members

### ISSUE THREAD

**Issue by alphanin9** [rayshader/cp2077-nativedb#205]
Would be pretty useful for RE purposes - less need to wade through 1000 inheritance levels in RED4ext SDK

**Comment by alphanin9** [comment]
For the same reason, it would also be pretty useful to have a "Show parent data" view of class where it also shows fields/funcs from the parent classes of said class

**Comment by poirierlouis** [comment]
Yes I thought about it a while ago. That's for another ticket though.
