### ISSUE TITLE
Browser "Search feature" doesn't match with page content

### ISSUE THREAD

**Issue by poirierlouis** [rayshader/cp2077-nativedb#30]
On Chrome / Edge at least.

Using browser Search feature to look for a function by name in a class doesn't work. Name exists in the page but browser is unable to detect/focus it.

Issue not present on Firefox.

**Comment by Roms1383** [comment]
### on Chrome
![image](https://github.com/rayshader/cp2077-nativedb/assets/21016014/aabd1ee5-6378-47e7-9567-d1dc23283f6f)
### on Edge
![image](https://github.com/rayshader/cp2077-nativedb/assets/21016014/f66216cd-44ab-48c4-86c5-4ab913c81943)
